### ISSUE TITLE
Mensagem de erro - senha invalida - quando encriptando um arquivo inválida 

### ISSUE THREAD

**Issue by BrunoScheltzke** [rodrigomaria1985/Dev10#3]
TC#2 - Jonas Ayre
![img_6007](https://cloud.githubusercontent.com/assets/18264163/26063278/f2d6f39e-3963-11e7-89b2-48ad3fc03aaa.JPG)

**Comment by AyresJonas** [comment]
Teste ocorrido como esperado.
