### ISSUE TITLE
TC #2 Recuperar arquivo encriptado Erro – Comprimento Senha

### ISSUE THREAD

**Issue by NataliaSchnechel** [rodrigomaria1985/Dev10#4]
**Apresenta um erro em inglês direcionado a desenvolvedores. Mensagem de erro:**
"_Ocorreu um erro. Info para desenvolvedores: O vetor de inicialização (IV) especificado não coincide com o tamanho do bloco deste algoritmo. System.Collections.ListDictionaryInternal em System.Security.Cryptography.RijndaelManagedTransform..ctor(Byte[] rgbKey, CipherMode mode, Byte[] rgbIV, Int32 blockSize, Int32 feedbackSize, PaddingMode PaddingValue, RijndaelManagedTransformMode transformMode) em System.Security.Cryptography.RijndaelManaged.NewEncryptor(Byte[] rgbKey, CipherMode mode, Byte[] rgbIV, Int32 feedbackSize, RijndaelManagedTransformMode encryptMode) em System.Security.Cryptography.RijndaelManaged.CreateDecryptor(Byte[] rgbKey, Byte[] rgbIV) em PEDRO.Controllers.HomeController.Decriptar(HttpPostedFileBase file, String userKey) na C:\Users\Rodrigo Maria\Documents\GitHub\Dev10\Implementacao\WEB\PEDRO\PEDRO\Controllers\HomeController.cs:linha 192_"

**Comment by rodrigomaria** [comment]
Qual seria o erro por apresentar essa mensagem?

**Comment by NataliaSchnechel** [comment]
Não se esperava uma mensagem, apenas se esperava que o usuário não recebesse o arquivo decriptado com sucesso
