### ISSUE TITLE
TC #4 Recuperar arquivo encriptado Erro – Sem digitação de senha

### ISSUE THREAD

**Issue by NataliaSchnechel** [rodrigomaria1985/Dev10#6]
**O erro apresentado é um erro generico e não uma mensagem exigindo a digitação de senha. Erro em inglês:**
“_Ocorreu um erro. Info para desenvolvedores: Comprimento inválido dos dados a serem descriptografados. System.Collections.ListDictionaryInternal em System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount) em System.Security.Cryptography.CryptoStream.FlushFinalBlock() em System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing) em System.IO.Stream.Close() em System.IO.Stream.Dispose() em PEDRO.Controllers.HomeController.Decriptar(HttpPostedFileBase file, String userKey) na C:\Users\Rodrigo” Maria\Documents\GitHub\Dev10\Implementacao\WEB\PEDRO\PEDRO\Controllers\HomeController.cs:linha 199_"

**Comment by rodrigomaria** [comment]
Qual seria o erro por apresentar essa mensagem?

**Comment by NataliaSchnechel** [comment]
Não se esperava uma mensagem, apenas se esperava que o usuário não recebesse o arquivo decriptado com sucesso
