### ISSUE TITLE
Nao foi possível encriptar um arquivo enquanto a pasta de destino de arquivos encriptados ser inexistente

### ISSUE THREAD

**Issue by BrunoScheltzke** [rodrigomaria1985/Dev10#7]
TC#2 - Step 2 - Clicar em dividir
Resultado - Foi mostrado uma tela de erro “Não foi possível localizar uma parte do caminho (caminho)”. 

Esse erro ocorreu ao tentar encriptar um arquivo após ter deletado a pasta de destino dos arquivos encriptados

**Comment by andriuswill** [comment]
Com a migração do sistema para web, a estrutura de arquivos se torna estática sem necessidade criá-la... OK
