### ISSUE TITLE
Foi possível dividir um arquivo com tamanho menor do que o limite informado (1 byte)

### ISSUE THREAD

**Issue by BrunoScheltzke** [rodrigomaria1985/Dev10#8]
TC#4 - Step 2 - Clicar em dividir
Resultado - Foi possível encriptar um arquivo de 1 byte em duas partes

Esperado - Sistema mostra uma página de erro, informando que o arquivo e muito pequeno para ser particionado.

**Comment by andriuswill** [comment]
Futuramente seria implementado um método para divisão de arquivo para este caso,  porém atualmente está funcionado. OK
